"""add problem solution metadata

Revision ID: c5757d033324
Revises: 90ffed4c26b5
Create Date: 2026-08-17 22:52:06.219940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5757d033324'
down_revision: Union[str, None] = '90ffed4c26b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('approach', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('time_complexity', sa.String(length=50), nullable=True))
    op.add_column('problems', sa.Column('space_complexity', sa.String(length=50), nullable=True))
    op.add_column('problems', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('problems', sa.Column('source_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'source_url')
    op.drop_column('problems', 'source')
    op.drop_column('problems', 'space_complexity')
    op.drop_column('problems', 'time_complexity')
    op.drop_column('problems', 'approach')
    # ### end Alembic commands ###
