"""add solution code metadata

Revision ID: ef4a4c9c7084
Revises: c5757d033324
Create Date: 2026-08-17 23:22:40.803770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4a4c9c7084'
down_revision: Union[str, None] = 'c5757d033324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('solution_code', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('programming_language', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'programming_language')
    op.drop_column('problems', 'solution_code')
    # ### end Alembic commands ###
